eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.74:8999/eureka/
server:
  port: 7778
spring:
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
